name: Keep Backend Awake
"on":
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend health check
        run: curl -f -s https://admanihomes.onrender.com/actuator/health
